// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmM3W2TfgNlPQfX0pluT-vr6ymSkbpJJ4',
    appId: '1:237387824540:web:663a5bd70e3c4c2aa61c59',
    messagingSenderId: '237387824540',
    projectId: 'learning-app-f7fcd',
    authDomain: 'learning-app-f7fcd.firebaseapp.com',
    storageBucket: 'learning-app-f7fcd.firebasestorage.app',
    measurementId: 'G-6SLNW7N8XP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbVm7Ph2lIh-5CaaukGgeXCa6Q8udpw1w',
    appId: '1:237387824540:android:9f954b7fc4822ac8a61c59',
    messagingSenderId: '237387824540',
    projectId: 'learning-app-f7fcd',
    storageBucket: 'learning-app-f7fcd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWfDoizNE0oS9idXkFj3C55VDJc1zatQM',
    appId: '1:237387824540:ios:b9994c64162fefaea61c59',
    messagingSenderId: '237387824540',
    projectId: 'learning-app-f7fcd',
    storageBucket: 'learning-app-f7fcd.firebasestorage.app',
    iosClientId: '237387824540-40c982bgf8tmsdbmogn6l57bs5rp0lj7.apps.googleusercontent.com',
    iosBundleId: 'com.example.appDevelopmentFinalAssessment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWfDoizNE0oS9idXkFj3C55VDJc1zatQM',
    appId: '1:237387824540:ios:b9994c64162fefaea61c59',
    messagingSenderId: '237387824540',
    projectId: 'learning-app-f7fcd',
    storageBucket: 'learning-app-f7fcd.firebasestorage.app',
    iosClientId: '237387824540-40c982bgf8tmsdbmogn6l57bs5rp0lj7.apps.googleusercontent.com',
    iosBundleId: 'com.example.appDevelopmentFinalAssessment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmM3W2TfgNlPQfX0pluT-vr6ymSkbpJJ4',
    appId: '1:237387824540:web:e03e9ef4a562d69da61c59',
    messagingSenderId: '237387824540',
    projectId: 'learning-app-f7fcd',
    authDomain: 'learning-app-f7fcd.firebaseapp.com',
    storageBucket: 'learning-app-f7fcd.firebasestorage.app',
    measurementId: 'G-05CRX3RQ0N',
  );
}
